accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login_user, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout_user, name='logout')
]

flinter/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name="index.html"), name="index"),
    path('accounts/', include('accounts.urls'), name="accounts"),
    path('projects/', include('projects.urls')),
    path('tasks/', include('tasks.urls')),
]

projects/urls.py
from django.urls import path

urlpatterns = [

]

tasks/urls.py
from django.urls import path

urlpatterns = [

]

accounts/models.py
from django.db import models

# Create your models here.

projects/models.py
from django.db import models

# Create your models here.
class Project(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField(max_length=200)
    due_date = models.DateTimeField()
    created_at = models.DateTimeField(auto_now_add=True)
    complete = models.BooleanField()

    def __str__(self):
        return self.name
    

tasks/models.py
from django.db import models
from projects.models import Project

# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=50)
    color = models.CharField(max_length=30)


class Task(models.Model):
    name = models.CharField(max_length=50)
    project = models.ForeignKey(
        Project, on_delete=models.CASCADE, related_name='tasks')
    category = models.ManyToManyField(Category)
    due_date = models.DateTimeField()
    complete = models.BooleanField()

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserCreateForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({'class': 'form-input'})
        self.fields['email'].widget.attrs.update({'class': 'form-input'})
        self.fields['password1'].widget.attrs.update({'class': 'form-input'})
        self.fields['password2'].widget.attrs.update({'class': 'form-input'})

accounts/views.py
from django.shortcuts import render, redirect
from .forms import UserCreateForm
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from .decorators import unauthenticated_user

# Create your views here.


@unauthenticated_user
def register(request):
    form = UserCreateForm()

    if request.method == "POST":
        form = UserCreateForm(request.POST)

        if form.is_valid():
            user = form.save()
            return redirect('accounts:login')
    return render(request, 'accounts/register.html', {'form': form})


@unauthenticated_user
def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('index')

    return render(request, 'accounts/login.html', {})


@login_required
def logout_user(request):
    logout(request)
    return redirect('index')

projects/views.py
from django.shortcuts import render

# Create your views here.

tasks/views.py
from django.shortcuts import render

# Create your views here.

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% block content %}
{% include "navbar.html" %}
<div class="background">
    <div class="form-container">
        <h1 class="mb-4">INICIAR SESIÓN</h1>
        <form method="POST">
            {% csrf_token %}
            <div class="mb-4">
                <label for="username">Nombre de Usuario</label>
                <input class="form-input" type="text" name="username">
            </div>
            <div class="mb-4">
                <label for="password">Contraseña</label>
                <input class="form-input" type="password" name="password">
            </div>
            <button class="submit-btn" type="submit">INICIAR SESIÓN</button>
            <p class="mt-4">No tienes cuenta? <a href="{% url 'accounts:register' %}">Registrarse</a></p>
        </form>
    </div>
</div>

{% endblock %}

accounts/templates/accounts/register.html
{% extends 'base.html' %}
{% block content %}
{% include "navbar.html" %}
<div class="background">
<div class="register-container">
    <h1 class="mb-4">Registrarse</h1>
    <form method="POST">
        {% csrf_token %}
        <div class="row mb-4">
            <div class="col">
                {{form.username.label}}
                {{form.username}}
            </div>
            <div class="col"> 
                {{form.email.label}}
                {{form.email}}
            </div>
        </div>
        <div class="row mb-4">
            <div class="col">
                {{form.password1.label}}
                {{form.password1}}
            </div>
            <div class="col"> 
                {{form.password2.label}}
                {{form.password2}}
            </div>
        </div>
        
        {{form.errors}}
        <button type="submit" class="submit-btn register-btn">Registrarse</button>
        <p class="mt-4">Ya tienes una cuenta? <a href="{% url 'accounts:login' %}">Iniciar Sesión</a></p>
    </form>
</div>
</div>

{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/forms.css' %}">
</head>
<body>

    {% block content %}

    {% endblock %}
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% include "navbar.html" %}
<h1>Hi</h1>

<!-- <div id="root"></div> 
<script src="{% static 'index-bundle.js' %}"></script> -->
{% endblock %}

templates/navbar.html
{% extends 'base.html' %}
{% block content %}

<nav>
    {% if user.is_authenticated %}
        <a href="{% url 'index' %}">Inicio</a>
        <a href="{% url 'accounts:logout' %}">Cerrar Sesión</a>
    {% else %}
        <a href="{% url 'index' %}">Inicio</a>
        <a href="{% url 'accounts:register' %}">Registrarse</a>
        <a href="{% url 'accounts:login' %}">Iniciar Sesión</a>
    {% endif %}
</nav>

{% endblock %}